spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
        highlight_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE # query 에서 ? 로 출력되는 부분에 들어가는 실제 값 표시