spring:
  application:
    name: delivery-service

  profiles:
    active: dev

  config:
    import: optional:file:.env[.properties]

  data:
    web:
      pageable:
        one-indexed-parameters: true

springdoc:
  api-docs:
    path: /api-docs

jwt:
  secret:
    key: ${JWT_SECRET_KEY}